name: Deploy Streamlit App with Google Analytics

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Change permissions
        run: chmod -R 777 /home/runner/work/alomranhr/alomranhr

      - name: Run Google Analytics injection script
        run: python add_ga.py

      - name: Start Streamlit
        run: nohup streamlit run app.py &

      - name: Ensure Streamlit started
        run: |
          if ! curl --silent --fail http://localhost:8501; then
            echo "Streamlit did not start within the expected time."
            exit 1
          fi
