name: Deploy Streamlit App with Google Analytics

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Adjust permissions
      run: chmod -R 777 ${{ github.workspace }}

    - name: Run Google Analytics injection script
      run: python add_ga.py

    - name: Start Streamlit
      run: streamlit run app.py
      env:
        STREAMLIT_SERVER_HEADLESS: true
