name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure permissions
      run: chmod -R 777 /home/runner/work/alomranhr/alomranhr

    - name: Run add_ga.py
      run: python add_ga.py

    - name: Verify changes
      run: cat static/index.html

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add static/index.html
        if ! git diff-index --quiet HEAD; then
          git commit -m "Add GA script to index.html"
          git push https://${{ secrets.EMPLOYEE_ATTRITION_PREDICTION }}@github.com/<Formshost>/alomranhr.git HEAD:main
        else
          echo "No changes to commit"
        fi

    - name: Start Streamlit
      run: |
        nohup streamlit run app.py &
        for i in {1..10}; do
          if curl --silent --fail http://localhost:8501; then
            echo "Streamlit started successfully."
            break
          else
            echo "Waiting for Streamlit to start..."
            sleep 10
          fi
        done
