name: Deploy Streamlit App with Google Analytics

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Google Analytics injection script
        run: |
          chmod -R 777 /home/runner/work/alomranhr/alomranhr
          python add_ga.py
          echo "Content of index.html after script execution:"
          cat static/index.html

      - name: Start Streamlit
        run: |
          nohup streamlit run app.py &

      - name: Confirm Streamlit is running
        run: |
          for i in {1..10}; do
            if curl --silent --fail http://localhost:8501; then
              echo "Streamlit started successfully."
              break
            else
              echo "Waiting for Streamlit to start..."
              sleep 10
            fi
          done
